#!/usr/bin/env python3
"""Exercise the actual Roslyn formatter, including its no-op detection contract."""
from pathlib import Path
import subprocess
import tempfile
import unittest

APP = Path('tools/SourceMaintenance/bin/Release/net10.0/SourceMaintenance.dll').resolve()

class FormattingTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        for name in ('src', 'samples', 'tests', 'tools'):
            (self.root / name).mkdir()

    def write(self, text, name='Example.cs'):
        path = self.root / 'src' / name
        path.write_text(text, encoding='utf-8')
        return path

    def run_tool(self, mode='--format', success=True):
        result = subprocess.run(['dotnet', str(APP), mode, str(self.root)], text=True, capture_output=True, timeout=30)
        self.assertEqual(success, result.returncode == 0, result.stdout + result.stderr)

    def test_expansion_and_check_without_writes(self):
        path = self.write('class A{void M(){int x=1;int y=2;}}')
        original = path.read_bytes()
        self.run_tool('--check-format', False)
        self.assertEqual(original, path.read_bytes())
        self.run_tool()
        self.assertIn('class A\n{', path.read_text())
        self.assertIn('int x = 1;\n', path.read_text())
        self.assertIn('int y = 2;\n', path.read_text())
        self.run_tool('--check-format')

    def test_literal_and_comment_contents(self):
        path = self.write('class A{ // preserved\nstring a=@"  first  \n second ";string b="a;{b}\\n";}')
        self.run_tool()
        self.assertIn('@"  first  \n second "', path.read_text())
        self.assertIn('"a;{b}\\n"', path.read_text())
        self.assertIn('// preserved', path.read_text())
        self.run_tool('--check-format')

    def test_conditional_branches(self):
        path = self.write('#if WINDOWS\nclass A{int X=1;}\n#else\nclass A{int X=2;}\n#endif\n#if DEBUG\nclass B{int Y=3;}\n#endif\n')
        self.run_tool()
        for expected in ('int X = 1;', 'int X = 2;', 'int Y = 3;', '#if WINDOWS'):
            self.assertIn(expected, path.read_text())
        self.run_tool('--check-format')

    def test_generated_and_reference_exclusions(self):
        self.write('class Ordinary{}')
        generated = self.write('// <auto-generated />\nclass A{}class B{}', 'Generated.g.cs')
        probe = self.root / 'tools' / 'ReferenceProbe' / 'Pinned.cs'
        probe.parent.mkdir()
        probe.write_text('class Pinned{int x=1;}')
        before = generated.read_bytes(), probe.read_bytes()
        self.run_tool()
        self.assertEqual(before, (generated.read_bytes(), probe.read_bytes()))
        self.run_tool('--check-format')

    def test_byte_idempotence(self):
        path = self.write('class A{void M(){if(true){return;}else{throw new System.Exception();}}}')
        self.run_tool()
        before = path.read_bytes()
        self.run_tool()
        self.assertEqual(before, path.read_bytes())
        self.assertTrue(before.endswith(b'\n'))
        self.assertFalse(before.startswith(b'\xef\xbb\xbf'))
        self.run_tool('--check-format')

    def test_no_source_cannot_pass(self):
        self.run_tool('--check-format', False)

if __name__ == '__main__':
    unittest.main()
