#!/usr/bin/env python3
"""Regression tests of the actual Roslyn source-organization executable."""
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET

APP = Path(os.environ.get("UNODOCK_SOURCE_MAINTENANCE_DLL", "tools/SourceMaintenance/bin/Release/net10.0/SourceMaintenance.dll")).resolve()


class SourceMaintenanceTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        for name in ("src", "samples", "tests", "tools"):
            (self.root / name).mkdir()

    def write(self, name, text):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def run_tool(self, mode="--apply", success=True):
        result = subprocess.run(["dotnet", str(APP), mode, str(self.root)], capture_output=True, text=True, timeout=30)
        self.assertEqual(success, result.returncode == 0, result.stdout + result.stderr)
        return result

    def sources(self):
        return {str(path.relative_to(self.root)): path.read_text() for path in self.root.rglob("*.cs")}

    def test_one_file_per_type_and_nested_identity(self):
        self.write("src/Mixed.cs", "namespace Example; public class A { public class Nested {} } public record B(int X);")
        self.run_tool()
        self.assertEqual({"src/A.cs", "src/B.cs"}, set(self.sources()))
        self.assertIn("class Nested", self.sources()["src/A.cs"])
        self.run_tool("--check")

    def test_conditional_types_are_not_lost(self):
        self.write("src/Mixed.cs", "namespace Example;\n#if WINDOWS\npublic class A { public int X = 1; }\n#else\npublic class A { public int X = 2; }\n#endif\npublic class B {}\n")
        self.run_tool()
        a = self.sources()["src/A.cs"]
        self.assertIn("X = 1", a)
        self.assertIn("X = 2", a)
        self.assertIn("#if WINDOWS", a)
        self.assertNotIn("class B", a)
        self.run_tool("--check")

    def test_conditional_declarations_in_separate_namespaces(self):
        self.write("src/Mixed.cs", "#if WINDOWS\nnamespace One { public class A {} public class B {} }\n#else\nnamespace Two { public class C {} public class D {} }\n#endif\n")
        self.run_tool()
        self.assertEqual(4, len(self.sources()))
        self.run_tool("--check")

    def test_linked_compile_items_follow_all_extracted_types(self):
        self.write("tests/Mixed.cs", "namespace Tests; public class A {} public class B {}")
        project = self.write("samples/App/App.csproj", '<Project><ItemGroup><Compile Include="../../tests/Mixed.cs" Link="Testing/Mixed.cs" Condition="true" /></ItemGroup></Project>')
        self.run_tool()
        entries = ET.parse(project).findall("./ItemGroup/Compile")
        self.assertEqual({"../../tests/A.cs", "../../tests/B.cs"}, {entry.get("Include") for entry in entries})
        self.assertEqual({"Testing/A.cs", "Testing/B.cs"}, {entry.get("Link") for entry in entries})
        self.assertTrue(all(entry.get("Condition") == "true" for entry in entries))
        self.assertTrue(all(line == line.rstrip() for line in project.read_text().splitlines()))

    def test_top_level_program_stays_in_original_file(self):
        self.write("src/Program.cs", 'using System; Console.WriteLine("retained"); class A {} class B {}')
        self.run_tool()
        self.assertEqual({"src/Program.cs", "src/A.cs", "src/B.cs"}, set(self.sources()))
        self.assertIn('Console.WriteLine("retained")', self.sources()["src/Program.cs"])
        self.assertNotIn("Console.WriteLine", self.sources()["src/A.cs"])
        self.run_tool("--check")

    def test_comments_and_using_alias_stay_with_type(self):
        self.write("src/Mixed.cs", "using Alias = System.String;\nnamespace Example;\n/// <summary>Type A documentation.</summary>\npublic class A { Alias text = \"kept\"; }\n/// <summary>Type B documentation.</summary>\npublic class B {}")
        self.run_tool()
        self.assertIn("Type A documentation", self.sources()["src/A.cs"])
        self.assertIn("Type B documentation", self.sources()["src/B.cs"])
        self.assertIn("using Alias = System.String", self.sources()["src/A.cs"])

    def test_file_local_type_is_rejected_without_partial_writes(self):
        self.write("src/First.cs", "class First {} class Second {}")
        self.write("src/Local.cs", "file class Local {} class Owner {}")
        before = self.sources()
        self.run_tool(success=False)
        self.assertEqual(before, self.sources())

    def test_generated_files_remain_byte_identical(self):
        path = self.write("src/Generated.g.cs", "// <auto-generated />\nclass A {} class B {}\n")
        before = path.read_bytes()
        self.run_tool()
        self.run_tool("--check")
        self.assertEqual(before, path.read_bytes())

    def test_idempotent_organization(self):
        self.write("src/Mixed.cs", "namespace Example; class A {} struct B {} delegate void C();")
        self.run_tool()
        before = self.sources()
        self.run_tool()
        self.assertEqual(before, self.sources())
        self.run_tool("--check")

    def test_check_rejects_multiple_types_without_editing(self):
        self.write("src/Mixed.cs", "class A {} class B {}")
        before = self.sources()
        self.run_tool("--check", success=False)
        self.assertEqual(before, self.sources())

    def test_assembly_attributes_are_kept_once(self):
        self.write("src/Mixed.cs", '[assembly: System.Reflection.AssemblyTitle("example")]\nnamespace Example; class A {} class B {}')
        self.run_tool()
        self.assertEqual(1, sum(text.count("AssemblyTitle") for text in self.sources().values()))

    def test_same_simple_name_does_not_overwrite_other_namespace(self):
        self.write("src/Mixed.cs", "namespace One { class A {} } namespace Two { class A {} }")
        self.run_tool()
        self.assertEqual(2, len(self.sources()))
        self.run_tool("--check")


if __name__ == "__main__":
    unittest.main()
