// Independent public-call observations. No upstream source bodies, private reflection,
// networking, resources or artwork are consumed. The pixel is generated by this probe.
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Data;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Xml.Linq;
using Xceed.Wpf.AvalonDock;

internal static class ExtendedConverterProbe
{
    [STAThread]
    private static int Main(string[] args)
    {
        if (args.Length != 1) throw new ArgumentException("Usage: ExtendedConverterProbe <output-directory>");
        Directory.CreateDirectory(args[0]);
        var images = Path.Combine(Environment.GetEnvironmentVariable("RUNNER_TEMP") ?? Path.GetTempPath(), "converter-reference", "probe-images");
        Directory.CreateDirectory(images);
        var file = Path.Combine(images, "probe-" + Guid.NewGuid().ToString("N") + ".png");
        try
        {
            var encoder = new PngBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(1, 1, 96, 96, PixelFormats.Bgra32, null, new byte[] { 0, 0, 0, 255 }, 4)));
            using (var stream = File.Create(file)) encoder.Save(stream);
            var output = new XElement("ExtendedConverterObservations");
            var converter = (IValueConverter)Activator.CreateInstance(typeof(DockingManager).Assembly.GetType("Xceed.Wpf.AvalonDock.Converters.UriSourceToBitmapImageConverter", true));
            foreach (var key in new[] { "null", "image", "relative-uri", "absolute-uri", "string", "empty-string", "integer", "boolean" })
                foreach (var target in new[] { "object", "image-source", "bitmap-image", "uri", "string" })
                    foreach (var reverse in new[] { false, true })
                    {
                        object input = key == "null" ? null : key == "image" ? (object)new BitmapImage() :
                            key == "relative-uri" ? new Uri("unodock-probe.png", UriKind.Relative) :
                            key == "absolute-uri" ? new Uri(file, UriKind.Absolute) : key == "string" ? "not-an-image" :
                            key == "empty-string" ? "" : key == "integer" ? (object)17 : true;
                        var targetType = target == "image-source" ? typeof(ImageSource) : target == "bitmap-image" ? typeof(BitmapImage) :
                            target == "uri" ? typeof(Uri) : target == "string" ? typeof(string) : typeof(object);
                        var record = new XElement("UriCase", new XAttribute("Input", key), new XAttribute("Target", target), new XAttribute("Reverse", reverse));
                        try { record.Add(Result(reverse ? converter.ConvertBack(input, targetType, null, CultureInfo.InvariantCulture) : converter.Convert(input, targetType, null, CultureInfo.InvariantCulture), input)); }
                        catch (Exception e) { record.Add(new XElement("Exception", new XAttribute("Type", e.GetType().FullName))); }
                        output.Add(record);
                    }
            var multi = (IMultiValueConverter)Activator.CreateInstance(typeof(DockingManager).Assembly.GetType("Xceed.Wpf.AvalonDock.Converters.AnchorableContextMenuHideVisibilityConverter", true));
            foreach (var key in new[] { "null-array", "empty", "visible", "collapsed", "visible,true", "visible,false", "collapsed,true", "collapsed,false", "visible,null", "visible,one", "visible,string", "visible,true,true", "unset,false", "nothing,false" })
                foreach (var reverse in new[] { false, true })
                {
                    object[] values = key == "null-array" ? null : key == "empty" ? new object[0] : key.Split(',').Select(Input).ToArray();
                    var record = new XElement("MultiCase", new XAttribute("Input", key), new XAttribute("Reverse", reverse));
                    try { record.Add(Result(reverse ? (object)multi.ConvertBack(Visibility.Visible, new[] { typeof(bool), typeof(bool) }, null, CultureInfo.InvariantCulture) : multi.Convert(values, typeof(Visibility), null, CultureInfo.InvariantCulture), values)); }
                    catch (Exception e) { record.Add(new XElement("Exception", new XAttribute("Type", e.GetType().FullName))); }
                    output.Add(record);
                }
            new XDocument(output).Save(Path.Combine(args[0], "converter-details.xml"));
            Console.WriteLine("Observed " + output.Elements().Count() + " extended converter calls.");
            return 0;
        }
        finally
        {
            // WPF's decoder may retain an on-demand file handle until this process
            // exits. The workflow removes the isolated directory after both probes.
            try { if (File.Exists(file)) File.Delete(file); } catch (IOException) { }
        }
    }
    private static object Input(string key)
    {
        switch (key)
        {
            case "visible": return Visibility.Visible; case "collapsed": return Visibility.Collapsed;
            case "true": return true; case "false": return false; case "null": return null;
            case "one": return 1; case "string": return "true";
            case "unset": return DependencyProperty.UnsetValue; case "nothing": return Binding.DoNothing;
            default: throw new ArgumentException(key);
        }
    }
    private static XElement Result(object result, object input)
    {
        if (result == null) return new XElement("Null");
        if (ReferenceEquals(result, Binding.DoNothing)) return new XElement("DoNothing");
        if (ReferenceEquals(result, DependencyProperty.UnsetValue)) return new XElement("UnsetValue");
        if (ReferenceEquals(result, input)) return new XElement("InputIdentity");
        if (result is Image control) return new XElement("Image", new XAttribute("SourceType", control.Source.GetType().FullName),
            new XAttribute("SameUri", control.Source is BitmapImage source && Equals(source.UriSource, input)), new XAttribute("Stretch", control.Stretch));
        if (result is BitmapImage image) return new XElement("BitmapImage", new XAttribute("SameUri", Equals(image.UriSource, input)));
        var type = result.GetType();
        if (type.IsEnum || type.IsPrimitive || result is string) return new XElement("Scalar", new XAttribute("Type", type.FullName), Convert.ToString(result, CultureInfo.InvariantCulture));
        return new XElement("Object", new XAttribute("Type", type.FullName));
    }
}
