<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF><IsPackable>false</IsPackable>
    <ImplicitUsings>disable</ImplicitUsings><Nullable>disable</Nullable>
    <StartupObject Condition="'$(StartupObject)' == ''">Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ReferenceUsing Include="Layout" />
    <ReferenceUsing Include="Layout.Serialization" />
  </ItemGroup>
  <Import Project="../ReferenceIdentity/ReferenceIdentity.targets" />
</Project>
