// <auto-generated />
#nullable enable
using UnoDock.Layout;
using UnoDock.Controls;
using UnoDock.Themes;
namespace UnoDock;
public partial class DockingManager
{
    public static readonly DependencyProperty AnchorableContextMenuProperty = DependencyProperty.Register(nameof(AnchorableContextMenu), typeof(MenuFlyout), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AnchorableContextMenu), e)));
    public MenuFlyout? AnchorableContextMenu { get => (MenuFlyout?)GetValue(AnchorableContextMenuProperty); set => SetValue(AnchorableContextMenuProperty, value); }
    public static readonly DependencyProperty DocumentContextMenuProperty = DependencyProperty.Register(nameof(DocumentContextMenu), typeof(MenuFlyout), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(DocumentContextMenu), e)));
    public MenuFlyout? DocumentContextMenu { get => (MenuFlyout?)GetValue(DocumentContextMenuProperty); set => SetValue(DocumentContextMenuProperty, value); }
    public static readonly DependencyProperty AnchorGroupTemplateProperty = DependencyProperty.Register(nameof(AnchorGroupTemplate), typeof(ControlTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AnchorGroupTemplate), e)));
    public ControlTemplate? AnchorGroupTemplate { get => (ControlTemplate?)GetValue(AnchorGroupTemplateProperty); set => SetValue(AnchorGroupTemplateProperty, value); }
    public static readonly DependencyProperty AnchorSideTemplateProperty = DependencyProperty.Register(nameof(AnchorSideTemplate), typeof(ControlTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AnchorSideTemplate), e)));
    public ControlTemplate? AnchorSideTemplate { get => (ControlTemplate?)GetValue(AnchorSideTemplateProperty); set => SetValue(AnchorSideTemplateProperty, value); }
    public static readonly DependencyProperty AnchorTemplateProperty = DependencyProperty.Register(nameof(AnchorTemplate), typeof(ControlTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AnchorTemplate), e)));
    public ControlTemplate? AnchorTemplate { get => (ControlTemplate?)GetValue(AnchorTemplateProperty); set => SetValue(AnchorTemplateProperty, value); }
    public static readonly DependencyProperty AnchorableHeaderTemplateProperty = DependencyProperty.Register(nameof(AnchorableHeaderTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorableHeaderTemplateChanged(e)));
    public DataTemplate? AnchorableHeaderTemplate { get => (DataTemplate?)GetValue(AnchorableHeaderTemplateProperty); set => SetValue(AnchorableHeaderTemplateProperty, value); }
    protected virtual void OnAnchorableHeaderTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorableHeaderTemplate), e);
    public static readonly DependencyProperty AnchorableTitleTemplateProperty = DependencyProperty.Register(nameof(AnchorableTitleTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorableTitleTemplateChanged(e)));
    public DataTemplate? AnchorableTitleTemplate { get => (DataTemplate?)GetValue(AnchorableTitleTemplateProperty); set => SetValue(AnchorableTitleTemplateProperty, value); }
    protected virtual void OnAnchorableTitleTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorableTitleTemplate), e);
    public static readonly DependencyProperty DocumentHeaderTemplateProperty = DependencyProperty.Register(nameof(DocumentHeaderTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentHeaderTemplateChanged(e)));
    public DataTemplate? DocumentHeaderTemplate { get => (DataTemplate?)GetValue(DocumentHeaderTemplateProperty); set => SetValue(DocumentHeaderTemplateProperty, value); }
    protected virtual void OnDocumentHeaderTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentHeaderTemplate), e);
    public static readonly DependencyProperty DocumentPaneMenuItemHeaderTemplateProperty = DependencyProperty.Register(nameof(DocumentPaneMenuItemHeaderTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentPaneMenuItemHeaderTemplateChanged(e)));
    public DataTemplate? DocumentPaneMenuItemHeaderTemplate { get => (DataTemplate?)GetValue(DocumentPaneMenuItemHeaderTemplateProperty); set => SetValue(DocumentPaneMenuItemHeaderTemplateProperty, value); }
    protected virtual void OnDocumentPaneMenuItemHeaderTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentPaneMenuItemHeaderTemplate), e);
    public static readonly DependencyProperty DocumentTitleTemplateProperty = DependencyProperty.Register(nameof(DocumentTitleTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentTitleTemplateChanged(e)));
    public DataTemplate? DocumentTitleTemplate { get => (DataTemplate?)GetValue(DocumentTitleTemplateProperty); set => SetValue(DocumentTitleTemplateProperty, value); }
    protected virtual void OnDocumentTitleTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentTitleTemplate), e);
    public static readonly DependencyProperty IconContentTemplateProperty = DependencyProperty.Register(nameof(IconContentTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(IconContentTemplate), e)));
    public DataTemplate? IconContentTemplate { get => (DataTemplate?)GetValue(IconContentTemplateProperty); set => SetValue(IconContentTemplateProperty, value); }
    public static readonly DependencyProperty LayoutItemTemplateProperty = DependencyProperty.Register(nameof(LayoutItemTemplate), typeof(DataTemplate), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLayoutItemTemplateChanged(e)));
    public DataTemplate? LayoutItemTemplate { get => (DataTemplate?)GetValue(LayoutItemTemplateProperty); set => SetValue(LayoutItemTemplateProperty, value); }
    protected virtual void OnLayoutItemTemplateChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LayoutItemTemplate), e);
    public static readonly DependencyProperty AnchorableHeaderTemplateSelectorProperty = DependencyProperty.Register(nameof(AnchorableHeaderTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorableHeaderTemplateSelectorChanged(e)));
    public DataTemplateSelector? AnchorableHeaderTemplateSelector { get => (DataTemplateSelector?)GetValue(AnchorableHeaderTemplateSelectorProperty); set => SetValue(AnchorableHeaderTemplateSelectorProperty, value); }
    protected virtual void OnAnchorableHeaderTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorableHeaderTemplateSelector), e);
    public static readonly DependencyProperty AnchorableTitleTemplateSelectorProperty = DependencyProperty.Register(nameof(AnchorableTitleTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorableTitleTemplateSelectorChanged(e)));
    public DataTemplateSelector? AnchorableTitleTemplateSelector { get => (DataTemplateSelector?)GetValue(AnchorableTitleTemplateSelectorProperty); set => SetValue(AnchorableTitleTemplateSelectorProperty, value); }
    protected virtual void OnAnchorableTitleTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorableTitleTemplateSelector), e);
    public static readonly DependencyProperty DocumentHeaderTemplateSelectorProperty = DependencyProperty.Register(nameof(DocumentHeaderTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentHeaderTemplateSelectorChanged(e)));
    public DataTemplateSelector? DocumentHeaderTemplateSelector { get => (DataTemplateSelector?)GetValue(DocumentHeaderTemplateSelectorProperty); set => SetValue(DocumentHeaderTemplateSelectorProperty, value); }
    protected virtual void OnDocumentHeaderTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentHeaderTemplateSelector), e);
    public static readonly DependencyProperty DocumentPaneMenuItemHeaderTemplateSelectorProperty = DependencyProperty.Register(nameof(DocumentPaneMenuItemHeaderTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentPaneMenuItemHeaderTemplateSelectorChanged(e)));
    public DataTemplateSelector? DocumentPaneMenuItemHeaderTemplateSelector { get => (DataTemplateSelector?)GetValue(DocumentPaneMenuItemHeaderTemplateSelectorProperty); set => SetValue(DocumentPaneMenuItemHeaderTemplateSelectorProperty, value); }
    protected virtual void OnDocumentPaneMenuItemHeaderTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentPaneMenuItemHeaderTemplateSelector), e);
    public static readonly DependencyProperty DocumentTitleTemplateSelectorProperty = DependencyProperty.Register(nameof(DocumentTitleTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentTitleTemplateSelectorChanged(e)));
    public DataTemplateSelector? DocumentTitleTemplateSelector { get => (DataTemplateSelector?)GetValue(DocumentTitleTemplateSelectorProperty); set => SetValue(DocumentTitleTemplateSelectorProperty, value); }
    protected virtual void OnDocumentTitleTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentTitleTemplateSelector), e);
    public static readonly DependencyProperty IconContentTemplateSelectorProperty = DependencyProperty.Register(nameof(IconContentTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(IconContentTemplateSelector), e)));
    public DataTemplateSelector? IconContentTemplateSelector { get => (DataTemplateSelector?)GetValue(IconContentTemplateSelectorProperty); set => SetValue(IconContentTemplateSelectorProperty, value); }
    public static readonly DependencyProperty LayoutItemTemplateSelectorProperty = DependencyProperty.Register(nameof(LayoutItemTemplateSelector), typeof(DataTemplateSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLayoutItemTemplateSelectorChanged(e)));
    public DataTemplateSelector? LayoutItemTemplateSelector { get => (DataTemplateSelector?)GetValue(LayoutItemTemplateSelectorProperty); set => SetValue(LayoutItemTemplateSelectorProperty, value); }
    protected virtual void OnLayoutItemTemplateSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LayoutItemTemplateSelector), e);
    public static readonly DependencyProperty AnchorablesSourceProperty = DependencyProperty.Register(nameof(AnchorablesSource), typeof(IEnumerable), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorablesSourceChanged(e)));
    public IEnumerable? AnchorablesSource { get => (IEnumerable?)GetValue(AnchorablesSourceProperty); set => SetValue(AnchorablesSourceProperty, value); }
    protected virtual void OnAnchorablesSourceChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorablesSource), e);
    public static readonly DependencyProperty DocumentsSourceProperty = DependencyProperty.Register(nameof(DocumentsSource), typeof(IEnumerable), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentsSourceChanged(e)));
    public IEnumerable? DocumentsSource { get => (IEnumerable?)GetValue(DocumentsSourceProperty); set => SetValue(DocumentsSourceProperty, value); }
    protected virtual void OnDocumentsSourceChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentsSource), e);
    public static readonly DependencyProperty LayoutUpdateStrategyProperty = DependencyProperty.Register(nameof(LayoutUpdateStrategy), typeof(ILayoutUpdateStrategy), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).PropertyChanged(nameof(LayoutUpdateStrategy), e)));
    public ILayoutUpdateStrategy? LayoutUpdateStrategy { get => (ILayoutUpdateStrategy?)GetValue(LayoutUpdateStrategyProperty); set => SetValue(LayoutUpdateStrategyProperty, value); }
    public static readonly DependencyProperty BottomSidePanelProperty = DependencyProperty.Register(nameof(BottomSidePanel), typeof(LayoutAnchorSideControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnBottomSidePanelChanged(e)));
    public LayoutAnchorSideControl? BottomSidePanel { get => (LayoutAnchorSideControl?)GetValue(BottomSidePanelProperty); set => SetValue(BottomSidePanelProperty, value); }
    protected virtual void OnBottomSidePanelChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(BottomSidePanel), e);
    public static readonly DependencyProperty LeftSidePanelProperty = DependencyProperty.Register(nameof(LeftSidePanel), typeof(LayoutAnchorSideControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLeftSidePanelChanged(e)));
    public LayoutAnchorSideControl? LeftSidePanel { get => (LayoutAnchorSideControl?)GetValue(LeftSidePanelProperty); set => SetValue(LeftSidePanelProperty, value); }
    protected virtual void OnLeftSidePanelChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LeftSidePanel), e);
    public static readonly DependencyProperty RightSidePanelProperty = DependencyProperty.Register(nameof(RightSidePanel), typeof(LayoutAnchorSideControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnRightSidePanelChanged(e)));
    public LayoutAnchorSideControl? RightSidePanel { get => (LayoutAnchorSideControl?)GetValue(RightSidePanelProperty); set => SetValue(RightSidePanelProperty, value); }
    protected virtual void OnRightSidePanelChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(RightSidePanel), e);
    public static readonly DependencyProperty TopSidePanelProperty = DependencyProperty.Register(nameof(TopSidePanel), typeof(LayoutAnchorSideControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnTopSidePanelChanged(e)));
    public LayoutAnchorSideControl? TopSidePanel { get => (LayoutAnchorSideControl?)GetValue(TopSidePanelProperty); set => SetValue(TopSidePanelProperty, value); }
    protected virtual void OnTopSidePanelChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(TopSidePanel), e);
    public static readonly DependencyProperty AutoHideWindowProperty = DependencyProperty.Register(nameof(AutoHideWindow), typeof(LayoutAutoHideWindowControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAutoHideWindowChanged(e)));
    public LayoutAutoHideWindowControl? AutoHideWindow { get => (LayoutAutoHideWindowControl?)GetValue(AutoHideWindowProperty); internal set => SetValue(AutoHideWindowProperty, value); }
    protected virtual void OnAutoHideWindowChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AutoHideWindow), e);
    public static readonly DependencyProperty LayoutRootPanelProperty = DependencyProperty.Register(nameof(LayoutRootPanel), typeof(LayoutPanelControl), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLayoutRootPanelChanged(e)));
    public LayoutPanelControl? LayoutRootPanel { get => (LayoutPanelControl?)GetValue(LayoutRootPanelProperty); set => SetValue(LayoutRootPanelProperty, value); }
    protected virtual void OnLayoutRootPanelChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LayoutRootPanel), e);
    public static readonly DependencyProperty AnchorablePaneControlStyleProperty = DependencyProperty.Register(nameof(AnchorablePaneControlStyle), typeof(Style), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnAnchorablePaneControlStyleChanged(e)));
    public Style? AnchorablePaneControlStyle { get => (Style?)GetValue(AnchorablePaneControlStyleProperty); set => SetValue(AnchorablePaneControlStyleProperty, value); }
    protected virtual void OnAnchorablePaneControlStyleChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AnchorablePaneControlStyle), e);
    public static readonly DependencyProperty DocumentPaneControlStyleProperty = DependencyProperty.Register(nameof(DocumentPaneControlStyle), typeof(Style), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnDocumentPaneControlStyleChanged(e)));
    public Style? DocumentPaneControlStyle { get => (Style?)GetValue(DocumentPaneControlStyleProperty); set => SetValue(DocumentPaneControlStyleProperty, value); }
    protected virtual void OnDocumentPaneControlStyleChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(DocumentPaneControlStyle), e);
    public static readonly DependencyProperty LayoutItemContainerStyleProperty = DependencyProperty.Register(nameof(LayoutItemContainerStyle), typeof(Style), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLayoutItemContainerStyleChanged(e)));
    public Style? LayoutItemContainerStyle { get => (Style?)GetValue(LayoutItemContainerStyleProperty); set => SetValue(LayoutItemContainerStyleProperty, value); }
    protected virtual void OnLayoutItemContainerStyleChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LayoutItemContainerStyle), e);
    public static readonly DependencyProperty LayoutItemContainerStyleSelectorProperty = DependencyProperty.Register(nameof(LayoutItemContainerStyleSelector), typeof(StyleSelector), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnLayoutItemContainerStyleSelectorChanged(e)));
    public StyleSelector? LayoutItemContainerStyleSelector { get => (StyleSelector?)GetValue(LayoutItemContainerStyleSelectorProperty); set => SetValue(LayoutItemContainerStyleSelectorProperty, value); }
    protected virtual void OnLayoutItemContainerStyleSelectorChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(LayoutItemContainerStyleSelector), e);
    public static readonly DependencyProperty ThemeProperty = DependencyProperty.Register(nameof(Theme), typeof(Theme), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnThemeChanged(e)));
    public Theme? Theme { get => (Theme?)GetValue(ThemeProperty); set => SetValue(ThemeProperty, value); }
    protected virtual void OnThemeChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(Theme), e);
    public static readonly DependencyProperty AllowMixedOrientationProperty = DependencyProperty.Register(nameof(AllowMixedOrientation), typeof(bool), typeof(DockingManager), new PropertyMetadata(false, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AllowMixedOrientation), e)));
    public bool AllowMixedOrientation { get => (bool)GetValue(AllowMixedOrientationProperty); set => SetValue(AllowMixedOrientationProperty, value); }
    public static readonly DependencyProperty AllowMovingFloatingWindowWithKeyboardProperty = DependencyProperty.Register(nameof(AllowMovingFloatingWindowWithKeyboard), typeof(bool), typeof(DockingManager), new PropertyMetadata(false, (d, e) => ((DockingManager)d).PropertyChanged(nameof(AllowMovingFloatingWindowWithKeyboard), e)));
    public bool AllowMovingFloatingWindowWithKeyboard { get => (bool)GetValue(AllowMovingFloatingWindowWithKeyboardProperty); private set => SetValue(AllowMovingFloatingWindowWithKeyboardProperty, value); }
    public static readonly DependencyProperty ShowSystemMenuProperty = DependencyProperty.Register(nameof(ShowSystemMenu), typeof(bool), typeof(DockingManager), new PropertyMetadata(true, (d, e) => ((DockingManager)d).PropertyChanged(nameof(ShowSystemMenu), e)));
    public bool ShowSystemMenu { get => (bool)GetValue(ShowSystemMenuProperty); set => SetValue(ShowSystemMenuProperty, value); }
    public static readonly DependencyProperty GridSplitterHeightProperty = DependencyProperty.Register(nameof(GridSplitterHeight), typeof(double), typeof(DockingManager), new PropertyMetadata(6d, (d, e) => ((DockingManager)d).PropertyChanged(nameof(GridSplitterHeight), e)));
    public double GridSplitterHeight { get => (double)GetValue(GridSplitterHeightProperty); set => SetValue(GridSplitterHeightProperty, value); }
    public static readonly DependencyProperty GridSplitterWidthProperty = DependencyProperty.Register(nameof(GridSplitterWidth), typeof(double), typeof(DockingManager), new PropertyMetadata(6d, (d, e) => ((DockingManager)d).PropertyChanged(nameof(GridSplitterWidth), e)));
    public double GridSplitterWidth { get => (double)GetValue(GridSplitterWidthProperty); set => SetValue(GridSplitterWidthProperty, value); }
    public static readonly DependencyProperty AutoHideWindowClosingTimerProperty = DependencyProperty.Register(nameof(AutoHideWindowClosingTimer), typeof(int), typeof(DockingManager), new PropertyMetadata(1500, (d, e) => ((DockingManager)d).OnAutoHideWindowClosingTimerChanged(e)));
    public int AutoHideWindowClosingTimer { get => (int)GetValue(AutoHideWindowClosingTimerProperty); set => SetValue(AutoHideWindowClosingTimerProperty, value); }
    protected virtual void OnAutoHideWindowClosingTimerChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(AutoHideWindowClosingTimer), e);
    public static readonly DependencyProperty ActiveContentProperty = DependencyProperty.Register(nameof(ActiveContent), typeof(object), typeof(DockingManager), new PropertyMetadata(null, (d, e) => ((DockingManager)d).OnActiveContentChanged(e)));
    public object? ActiveContent { get => (object?)GetValue(ActiveContentProperty); set => SetValue(ActiveContentProperty, value); }
    protected virtual void OnActiveContentChanged(DependencyPropertyChangedEventArgs e) => PropertyChanged(nameof(ActiveContent), e);
}
