#!/usr/bin/env python3
"""Format every handwritten C# input using an isolated SDK formatting project.

A deliberate bad-input sentinel proves that the selected SDK loads EditorConfig
and applies it. The project includes only audited source paths, no application
projects, generators, analyzers or build targets. Four preprocessing configurations
cover conditional Windows and Debug code without altering executable tokens.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
CONFIGURATIONS = ("", "WINDOWS", "DEBUG", "WINDOWS;DEBUG")


def source_files(root: Path) -> list[Path]:
    files = []
    for directory in ("src", "samples", "tests", "tools"):
        for path in (root / directory).rglob("*.cs"):
            relative = path.relative_to(root)
            if {"bin", "obj", "node_modules"}.intersection(relative.parts):
                continue
            if path.name.endswith(".g.cs") or relative.as_posix().startswith("tools/ReferenceProbe/"):
                continue
            if any("<auto-generated" in line.lower() for line in path.read_text(encoding="utf-8-sig").splitlines()[:3]):
                continue
            files.append(path.resolve())
    return sorted(files)


def invoke(root: Path, files: list[Path], verify: bool, defines: str = "") -> subprocess.CompletedProcess:
    with tempfile.TemporaryDirectory(prefix="unodock-format-project-") as directory:
        project = ET.Element("Project", Sdk="Microsoft.NET.Sdk")
        properties = ET.SubElement(project, "PropertyGroup")
        for key, value in {
            "TargetFramework": "net10.0", "EnableDefaultCompileItems": "false",
            "LangVersion": "preview", "DefineConstants": defines,
            "GenerateAssemblyInfo": "false", "IsPackable": "false",
        }.items():
            ET.SubElement(properties, key).text = value
        items = ET.SubElement(project, "ItemGroup")
        for path in files:
            ET.SubElement(items, "Compile", Include=str(path))
        ET.SubElement(items, "EditorConfigFiles", Include=str(root / ".editorconfig"))
        target = Path(directory) / "Formatting.csproj"
        ET.ElementTree(project).write(target, encoding="utf-8", xml_declaration=True)
        restored = subprocess.run(["dotnet", "restore", str(target), "--verbosity", "quiet"],
            cwd=root, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=120)
        if restored.returncode != 0:
            raise RuntimeError(restored.stdout + restored.stderr)
        command = ["dotnet", "format", "whitespace", str(target), "--no-restore", "--verbosity", "normal"]
        if verify:
            command.append("--verify-no-changes")
        return subprocess.run(command, cwd=root, text=True, encoding="utf-8", errors="replace", capture_output=True, timeout=120)


def sentinel(root: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="unodock-formatter-") as directory:
        fixture = Path(directory)
        shutil.copyfile(root / ".editorconfig", fixture / ".editorconfig")
        path = fixture / "Example.cs"
        original = "namespace FormatterProbe;public class Example{public void Run(){int a=1;int b=2;}}\n"
        path.write_text(original, encoding="utf-8")
        initial = invoke(fixture, [path], True)
        if initial.returncode == 0 or path.read_text() != original:
            raise RuntimeError("Verification failed to detect the unformatted sentinel without changing it.\n" + initial.stdout + initial.stderr)
        applied = invoke(fixture, [path], False)
        if applied.returncode != 0:
            raise RuntimeError(applied.stdout + applied.stderr)
        text = path.read_text()
        if not re.search(r"class Example\s*\n\s*\{", text) or "int a = 1;" not in text:
            raise RuntimeError("EditorConfig brace/spacing rules were not applied: " + repr(text) + "\n" + applied.stdout + applied.stderr)
        final = invoke(fixture, [path], True)
        if final.returncode != 0:
            raise RuntimeError("Formatter sentinel was not idempotent.\n" + final.stdout + final.stderr)
        print("Formatter sentinel: detects bad input, applies EditorConfig and verifies idempotently.", flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--sentinel-only", action="store_true")
    args = parser.parse_args()
    sentinel(ROOT)
    if args.sentinel_only:
        return 0
    files = source_files(ROOT)
    if not files:
        raise RuntimeError("No handwritten C# files selected.")
    before = {path: hashlib.sha256(path.read_bytes()).hexdigest() for path in files}
    failures = []
    for defines in CONFIGURATIONS:
        print(f"Formatting {len(files)} explicit source files, symbols={defines or '(none)'}, verify={args.check}.", flush=True)
        result = invoke(ROOT, files, args.check, defines)
        print(result.stdout, end="", flush=True)
        print(result.stderr, end="", flush=True)
        if result.returncode != 0:
            failures.append(defines)
    modified = [path for path in files if before[path] != hashlib.sha256(path.read_bytes()).hexdigest()]
    print(f"Explicit source coverage: {len(files)} files; {len(modified)} changed; {len(failures)} failing configurations.", flush=True)
    if args.check and modified:
        raise RuntimeError("Verification unexpectedly changed source files.")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
