"""Deterministic WinUI property adapters from the pinned declaration-only contract.
Only public property names and types are read; implementation and defaults are independent.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
lines = (ROOT / 'contracts/avalondock.txt').read_text(encoding='utf-8').splitlines()
namespace = 'Xceed.Wpf.AvalonDock'
classes = [namespace + '.DockingManager', namespace + '.Controls.LayoutItem', namespace + '.Controls.LayoutAnchorableItem', namespace + '.Controls.LayoutDocumentItem']
defaults = {'AllowMixedOrientation': 'true', 'AllowMovingFloatingWindowWithKeyboard': 'true', 'ShowSystemMenu': 'true', 'GridSplitterHeight': '6d', 'GridSplitterWidth': '6d', 'AutoHideWindowClosingTimer': '400', 'CanClose': 'true', 'CanFloat': 'true', 'CanHide': 'true'}
skip = {'Layout', 'FloatingWindows', 'LogicalChildrenPublic', 'View', 'LayoutElement', 'Model'}
for full in classes:
    ns, cls = full.rsplit('.', 1)
    body = ['// <auto-generated />', '#nullable enable', 'using Xceed.Wpf.AvalonDock.Layout;', 'using Xceed.Wpf.AvalonDock.Controls;', 'using Xceed.Wpf.AvalonDock.Themes;', f'namespace {ns};', f'public {"abstract " if cls == "LayoutItem" else ""}partial class {cls}', '{']
    for line in lines:
        if not line.startswith(full + ' | '): continue
        match = re.fullmatch(r'public (\S+) (\w+) \{ get;(?P<set>.*) \}', line.split(' | ')[1])
        if not match: continue
        typ, name = match[1], match[2]
        if name in skip: continue
        typ = {'ContextMenu': 'MenuFlyout'}.get(typ, typ)
        value_type = typ in {'bool', 'int', 'double'}
        nullable = typ if value_type else typ + '?'
        default = defaults.get(name, {'bool': 'false', 'int': '0', 'double': '0d'}.get(typ, 'null'))
        callback = f'(({cls})d).PropertyChanged(nameof({name}), e)' if cls == 'DockingManager' else f'(({cls})d).OnAdapterPropertyChanged(nameof({name}), e)'
        setter = 'private ' if name == 'AllowMovingFloatingWindowWithKeyboard' else 'internal ' if name == 'AutoHideWindow' else ''
        body.extend([f'    public static readonly DependencyProperty {name}Property = DependencyProperty.Register(nameof({name}), typeof({typ}), typeof({cls}), new PropertyMetadata({default}, (d, e) => {callback}));', f'    public {nullable} {name} {{ get => ({nullable})GetValue({name}Property); {setter}set => SetValue({name}Property, value); }}'])
    body.append('}')
    folder = ROOT / 'src/UnoDock' / ('Controls' if '.Controls.' in full else '')
    (folder / (cls + '.Properties.g.cs')).write_text('\n'.join(body) + '\n', encoding='utf-8')
