// <auto-generated />
#nullable enable
using Xceed.Wpf.AvalonDock.Layout;
using Xceed.Wpf.AvalonDock.Controls;
using Xceed.Wpf.AvalonDock.Themes;
namespace Xceed.Wpf.AvalonDock.Controls;
public abstract partial class LayoutItem
{
    public static readonly DependencyProperty ActivateCommandProperty = DependencyProperty.Register(nameof(ActivateCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(ActivateCommand), e)));
    public ICommand? ActivateCommand { get => (ICommand?)GetValue(ActivateCommandProperty); set => SetValue(ActivateCommandProperty, value); }
    public static readonly DependencyProperty CloseAllButThisCommandProperty = DependencyProperty.Register(nameof(CloseAllButThisCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(CloseAllButThisCommand), e)));
    public ICommand? CloseAllButThisCommand { get => (ICommand?)GetValue(CloseAllButThisCommandProperty); set => SetValue(CloseAllButThisCommandProperty, value); }
    public static readonly DependencyProperty CloseAllCommandProperty = DependencyProperty.Register(nameof(CloseAllCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(CloseAllCommand), e)));
    public ICommand? CloseAllCommand { get => (ICommand?)GetValue(CloseAllCommandProperty); set => SetValue(CloseAllCommandProperty, value); }
    public static readonly DependencyProperty CloseCommandProperty = DependencyProperty.Register(nameof(CloseCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(CloseCommand), e)));
    public ICommand? CloseCommand { get => (ICommand?)GetValue(CloseCommandProperty); set => SetValue(CloseCommandProperty, value); }
    public static readonly DependencyProperty DockAsDocumentCommandProperty = DependencyProperty.Register(nameof(DockAsDocumentCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(DockAsDocumentCommand), e)));
    public ICommand? DockAsDocumentCommand { get => (ICommand?)GetValue(DockAsDocumentCommandProperty); set => SetValue(DockAsDocumentCommandProperty, value); }
    public static readonly DependencyProperty FloatCommandProperty = DependencyProperty.Register(nameof(FloatCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(FloatCommand), e)));
    public ICommand? FloatCommand { get => (ICommand?)GetValue(FloatCommandProperty); set => SetValue(FloatCommandProperty, value); }
    public static readonly DependencyProperty MoveToNextTabGroupCommandProperty = DependencyProperty.Register(nameof(MoveToNextTabGroupCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(MoveToNextTabGroupCommand), e)));
    public ICommand? MoveToNextTabGroupCommand { get => (ICommand?)GetValue(MoveToNextTabGroupCommandProperty); set => SetValue(MoveToNextTabGroupCommandProperty, value); }
    public static readonly DependencyProperty MoveToPreviousTabGroupCommandProperty = DependencyProperty.Register(nameof(MoveToPreviousTabGroupCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(MoveToPreviousTabGroupCommand), e)));
    public ICommand? MoveToPreviousTabGroupCommand { get => (ICommand?)GetValue(MoveToPreviousTabGroupCommandProperty); set => SetValue(MoveToPreviousTabGroupCommandProperty, value); }
    public static readonly DependencyProperty NewHorizontalTabGroupCommandProperty = DependencyProperty.Register(nameof(NewHorizontalTabGroupCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(NewHorizontalTabGroupCommand), e)));
    public ICommand? NewHorizontalTabGroupCommand { get => (ICommand?)GetValue(NewHorizontalTabGroupCommandProperty); set => SetValue(NewHorizontalTabGroupCommandProperty, value); }
    public static readonly DependencyProperty NewVerticalTabGroupCommandProperty = DependencyProperty.Register(nameof(NewVerticalTabGroupCommand), typeof(ICommand), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(NewVerticalTabGroupCommand), e)));
    public ICommand? NewVerticalTabGroupCommand { get => (ICommand?)GetValue(NewVerticalTabGroupCommandProperty); set => SetValue(NewVerticalTabGroupCommandProperty, value); }
    public static readonly DependencyProperty IconSourceProperty = DependencyProperty.Register(nameof(IconSource), typeof(ImageSource), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(IconSource), e)));
    public ImageSource? IconSource { get => (ImageSource?)GetValue(IconSourceProperty); set => SetValue(IconSourceProperty, value); }
    public static readonly DependencyProperty CanCloseProperty = DependencyProperty.Register(nameof(CanClose), typeof(bool), typeof(LayoutItem), new PropertyMetadata(true, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(CanClose), e)));
    public bool CanClose { get => (bool)GetValue(CanCloseProperty); set => SetValue(CanCloseProperty, value); }
    public static readonly DependencyProperty CanFloatProperty = DependencyProperty.Register(nameof(CanFloat), typeof(bool), typeof(LayoutItem), new PropertyMetadata(true, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(CanFloat), e)));
    public bool CanFloat { get => (bool)GetValue(CanFloatProperty); set => SetValue(CanFloatProperty, value); }
    public static readonly DependencyProperty IsActiveProperty = DependencyProperty.Register(nameof(IsActive), typeof(bool), typeof(LayoutItem), new PropertyMetadata(false, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(IsActive), e)));
    public bool IsActive { get => (bool)GetValue(IsActiveProperty); set => SetValue(IsActiveProperty, value); }
    public static readonly DependencyProperty IsSelectedProperty = DependencyProperty.Register(nameof(IsSelected), typeof(bool), typeof(LayoutItem), new PropertyMetadata(false, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(IsSelected), e)));
    public bool IsSelected { get => (bool)GetValue(IsSelectedProperty); set => SetValue(IsSelectedProperty, value); }
    public static readonly DependencyProperty ContentIdProperty = DependencyProperty.Register(nameof(ContentId), typeof(string), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(ContentId), e)));
    public string? ContentId { get => (string?)GetValue(ContentIdProperty); set => SetValue(ContentIdProperty, value); }
    public static readonly DependencyProperty TitleProperty = DependencyProperty.Register(nameof(Title), typeof(string), typeof(LayoutItem), new PropertyMetadata(null, (d, e) => ((LayoutItem)d).OnAdapterPropertyChanged(nameof(Title), e)));
    public string? Title { get => (string?)GetValue(TitleProperty); set => SetValue(TitleProperty, value); }
}
